apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat.fullname" . }}-redis
  labels:
    {{- include "chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "chat.redisSelector" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
